# Notebook Imports

In [1]:
import pandas as pd
import numpy as np

# Constants

In [98]:
TRAINING_DATA_FILE = 'SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'SpamData/02_Training/test-data.txt'

TOKEN_SPAM_PROB_FILE = 'SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'SpamData/03_Testing/prob-all-tokens.txt'

TEST_FEATURE_MATRIX = 'SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'SpamData/03_Testing/test-target.txt'

VOCAB_SIZE = 2500

# Read and Load Features from .txt Files into NumPy Array

In [3]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, dtype=int, delimiter=' ')
sparse_test_data = np.loadtxt(TEST_DATA_FILE, dtype=int, delimiter=' ')

In [4]:
print('Nr of rows in training file: ', len(sparse_train_data))
print('Nr of rows in test file: ', sparse_test_data.shape[0])

Nr of rows in training file:  258360
Nr of rows in test file:  117776


In [5]:
print('Nr of emails in training file: ', len(np.unique(sparse_train_data[:,0])))
print('Nr of emails in training file: ', np.unique(sparse_train_data[:,0]).size)

Nr of emails in training file:  4013
Nr of emails in training file:  4013


In [6]:
print('Nr of emails in training file: ', len(np.unique(sparse_test_data[:,0])))
print('Nr of emails in training file: ', np.unique(sparse_test_data[:,0]).size)

Nr of emails in training file:  1724
Nr of emails in training file:  1724


### How to create an Empty DataFrame

In [7]:
column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
column_names[:5]

['DOC_ID', 'CATEGORY', 0, 1, 2]

In [8]:
index_names = np.unique(sparse_train_data[:,0])
index_names[:5]

array([0, 1, 2, 3, 4])

In [9]:
full_train_data = pd.DataFrame(index=index_names, columns=column_names)
full_train_data

DOC_ID CATEGORY    0    1    2    3    4    5    6    7  ... 2490 2491  \
0       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
1       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
2       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
3       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
4       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
...     ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5789    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5790    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5791    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5794    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5795    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   

     2492 2493 2494 2495 2496 2497 2498 2499  
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  ...  
5789  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5790  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5791  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5794  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5795  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[4013 rows x 2502 columns]

In [10]:
full_train_data.fillna(0, inplace=True)
full_train_data.head()

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

   2494  2495  2496  2497  2498  2499  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 2502 columns]

In [11]:
sparse_train_data[10:13]

array([[ 0, 31,  1,  1],
       [ 0, 33,  1,  1],
       [ 0, 44,  1,  1]])

In [12]:
sparse_train_data[10:13, 2]

array([1, 1, 1])

In [13]:
sparse_train_data[10, 2]

1

In [14]:
sparse_train_data[10][2]

1

# Create a Full Matrix from a Sparse Matrix

In [35]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
    
    
    
    column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, nr_words))
    index_names = np.unique(sparse_train_data[:,0])
    full_train_data = pd.DataFrame(index=index_names, columns=column_names)
    full_train_data.fillna(0, inplace=True)
    
    for i in range(sparse_matrix.shape[0]):
        doc_id = sparse_matrix[i][doc_idx]
        label = sparse_matrix[i][cat_idx]
        occurance = sparse_matrix[i][freq_idx]
        word_ID = sparse_matrix[i][word_idx]
        
        full_train_data.loc[doc_id, 'DOC_ID']=doc_id
        full_train_data.loc[doc_id, 'CATEGORY']=label
        full_train_data.loc[doc_id, word_ID]=occurance
        
        
    full_train_data.set_index('DOC_ID' ,inplace=True)
    return full_train_data

In [36]:
%%time

full_train_data = make_full_matrix(sparse_train_data, VOCAB_SIZE)

CPU times: total: 1min 46s
Wall time: 1min 46s


In [37]:
full_train_data.head()

CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  14  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  

[5 rows x 2501 columns]

# Training the Naive Bayes Model

## Calculating the Probability of Spam

In [40]:
prob_spam = full_train_data['CATEGORY'].sum() / full_train_data.shape[0]
print('Probability of spam is', prob_spam)

Probability of spam is 0.310989284824321


## Total Number of Words / Tokens

In [47]:
train_feature_data = full_train_data.loc[:, full_train_data.columns != 'CATEGORY']
# train_feature_data = full_train_data.drop(['CATEGORY'], axis=1)
train_feature_data

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    14     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5789       3     1     0     1     0     0     0     1     0     0  ...     0   
5790       1     1     1     0     0     0     1     0     0     0  ...     0   
5791       3     1     0     1     1     0     0     0     1     0  ...     0   
5794       1     1     1     0     0     1     2     0     0     1  ...     0   
5795       3     4     2     0     5     0     3     0     0     4  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0     0     0     0  
5790       0     0     0     0     0     0     0     0     0  
5791       0     0     1     0     0     0     0     0     0  
5794       0     0     0     0     0     0     0     0     0  
5795       0     0     0     0     0     0     0     0     0  

[4013 rows x 2500 columns]

In [51]:
email_lengths = train_feature_data.sum(axis=1)
email_lengths.shape

(4013,)

In [52]:
total_wc = email_lengths.sum()
total_wc

429241

# Number of Tokens in Spam & Ham Emails

In [58]:
spam_feature_data = train_feature_data[full_train_data['CATEGORY']==1]
ham_feature_data = train_feature_data[full_train_data['CATEGORY']==0]

In [67]:
spam_lengths = spam_feature_data.sum(axis=1)
ham_lengths = ham_feature_data.sum(axis=1)

In [68]:
spam_wc = spam_lengths.sum()
spam_wc

176334

In [69]:
nonspam_wc = ham_lengths.sum()
nonspam_wc

252907

In [70]:
email_lengths.shape[0] - spam_lengths.shape[0] - ham_lengths.shape[0]

0

In [76]:
print(f'Average nr of words in spam emails {spam_wc / spam_lengths.shape[0]:0.0f}')
print(f'Average nr of words in ham emails {nonspam_wc / ham_lengths.shape[0]:0.0f}')

Average nr of words in spam emails 141
Average nr of words in ham emails 91


## Summing the Tokens Occuring in Spam

In [77]:
spam_feature_data.shape

(1248, 2500)

In [80]:
summed_spam_tokens = spam_feature_data.sum(axis=0) + 1
summed_spam_tokens.shape

(2500,)

In [81]:
summed_spam_tokens.tail()

2495     3
2496     2
2497    17
2498    15
2499     2
dtype: int64

## Summing the Tokens Occuring in Ham

In [82]:
ham_feature_data.shape

(2765, 2500)

In [83]:
summed_ham_tokens = ham_feature_data.sum(axis=0) + 1
summed_ham_tokens.shape

(2500,)

In [84]:
summed_ham_tokens.tail()

2495    27
2496    35
2497    20
2498    15
2499    28
dtype: int64

## P(Token | Spam) - Probability that a Token Occurs given the Email is Spam

In [89]:
prob_tokens_spam = summed_spam_tokens / (spam_wc + VOCAB_SIZE)

In [90]:
prob_tokens_spam[:5]

0    0.012184
1    0.005228
2    0.006805
3    0.011307
4    0.006816
dtype: float64

In [91]:
prob_tokens_spam.sum()

1.0

## P(Token | Ham) - Probability that a Token Occurs given the Email is Nonspam

In [92]:
prob_tokens_nonspam = summed_ham_tokens / (nonspam_wc + VOCAB_SIZE)

In [93]:
prob_tokens_nonspam[:5]

0    0.021472
1    0.010141
2    0.008007
3    0.003673
4    0.006311
dtype: float64

In [94]:
prob_tokens_nonspam.sum()

1.0

# P(Token) - Probability that Token Occurs 

In [95]:
prob_tokens_all = train_feature_data.sum(axis=1) / (total_wc)

In [96]:
prob_tokens_all.sum()

1.0

# Save the Trained Model

In [99]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_tokens_nonspam)
np.savetxt(TOKEN_ALL_PROB_FILE, prob_tokens_all)

# Prepare Test Data

In [ ]:
%%time

full_test_data = make_full_matrix(sparse_test_data, VOCAB_SIZE)

In [ ]:
X_test = full_test_data.loc[:, full_test_data.columns != 'CATEGORY']
y_test = full_test_data.CATEGORY

In [ ]:
np.savetxt(TEST_TARGET_FILE, y_test)
np.savetxt(TEST_FEATURE_MATRIX, X_test)